apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE/BACKEND
          env:
          - name: PORT
            value: "3000"
          - name: TODOS_PATH
            value: "/api/todos"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-backend-postgres-secret
                key: POSTGRES_PASSWORD
          - name: DATABASE_URL
            value: "postgres://postgres:$(POSTGRES_PASSWORD)@todo-backend-postgres-svc"
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
  strategy:
    type: Recreate
