apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-app-static-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
